language: php

php:
    - 5.4

before_install:
    - composer self-update
    - composer update

before_script:
    - mysql -e 'create database phpbr_en;'
    - composer install -n

script:
    - bin/phpunit -c app src/Phpbr/AppBundle/

notifications:
    email:
        - phpbr@yahoo.ca

