home_admin:
    path: /
    defaults: { _controller: "PhpbrAppBundle:Admin\Admin:index" }

admin_artigos:
    resource: "@PhpbrAppBundle/Resources/config/routing/admin/artigo.yml"
    prefix: /artigos

admin_forum:
    resource: "@PhpbrAppBundle/Resources/config/routing/admin/forum.yml"
    prefix: /forum
