home_admin:
    path: /
    defaults: { _controller: "PhpbrAppBundle:Admin\Admin:index" }

admin_articles:
    resource: "@PhpbrAppBundle/Resources/config/routing/admin/articles.yml"
    prefix: /artigos

admin_forum:
    resource: "@PhpbrAppBundle/Resources/config/routing/admin/forum.yml"
    prefix: /forum
