home_admin:
    path: /admin
    defaults: { _controller: "PhpbrAppBundle:Admin\Admin:index" }

admin_articles:
    resource: "@PhpbrAppBundle/Resources/config/routing/admin/article.yml"

admin_forum:
    resource: "@PhpbrAppBundle/Resources/config/routing/admin/forum.yml"
