phpbr_event_view_all:
    path:     /events
    defaults: { _controller: "PhpbrAppBundle:Event:viewAll" }

phpbr_new_event:
    path:     /events/new
    defaults: { _controller: "PhpbrAppBundle:Event:new" }

phpbr_list_my_events:
    path:     /events/my-events
    defaults: { _controller: "PhpbrAppBundle:Event:listMyEvents" }

phpbr_event_delete:
    path:     /events/delete/{id}
    defaults: { _controller: "PhpbrAppBundle:Event:delete" }

phpbr_event_edit:
    path:     /events/edit/{id}
    defaults: { _controller: "PhpbrAppBundle:Event:edit" }

phpbr_event_view:
    path:     /event/{slug}
    defaults: { _controller: "PhpbrAppBundle:Event:view" }
