list_my_articles:
    path:     /my-articles
    defaults: { _controller: PhpbrAppBundle:Article:listMyArticles }

delete_my_article:
    path:     /my-articles/{id}/delete
    defaults: { _controller: PhpbrAppBundle:Article:delete }

article_edit:
    path:     /my-articles/{id}/edit
    defaults: { _controller: PhpbrAppBundle:Article:edit }

article_update:
    path:     /my-articles/{id}
    defaults: { _controller: PhpbrAppBundle:Article:update }
    requirements: { _method: post|put }
