parameters:
    database_driver:   pdo_mysql
    database_host:     '127.0.0.1'
    database_port:     ~
    database_name:     phpbr_en
    database_user:     ~
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            pt_BR

    # A secret key that's used to generate certain security-related tokens
    secret:            'php-br.org'

    debug_toolbar:          false
    debug_redirects:        false
    use_assetic_controller: true

    knp_disqus.api_key: XXX
    knp_disqus.secret_key: XXX # optional, for SSO auth only
    knp_disqus.lorem.shortname: "php-br.org"

    articles_per_page: 10
    coles_por_pagina: 5

    website: "php-br.dev"
    
    irc.bot.api_key: ~

