phpbr_api_get_article:
    path: /api/v1/artigo/{id}
    defaults: { _controller: "PhpbrAppBundle:ArticleApi:getArticle" }
    requirements:
        _method: GET
        id: "\d+"


phpbr_api_put_irc:
    path: /api/v1/irc/{api_key}/{nicks}
    defaults: { _controller: "PhpbrAppBundle:IrcApi:putIrc" }
    requirements:
        _method: PUT


phpbr_api_get_irc:
    path: /api/v1/irc
    defaults: { _controller: "PhpbrAppBundle:IrcApi:getNicks" }
    requirements:
        _method: GET


phpbr_api_get_no_comments_article:
    path: /api/v1/quantity-of-comments/{slug}
    defaults: { _controller: "PhpbrAppBundle:ArticleApi:getNoComments" }
    requirements:
        _method: GET
