list_articles:
    path:   /articles
    defaults: { _controller: PhpbrAppBundle:Article:list }

new_article:
    path:     /articles/new
    defaults: { _controller: PhpbrAppBundle:Article:new }

read_article:
    path: /article/{slug}
    defaults: { _controller: PhpbrAppBundle:Article:read }
