forum_index:
    path:     /
    defaults: { _controller: "PhpbrAppBundle:Forum\Categoria:index" }
    host:     %website%

forum_ver_categoria:
    path:     /categoria/{slug}
    defaults: { _controller: "PhpbrAppBundle:Forum\Categoria:verCategoria" }
    host:     %website%

forum_ver_topico:
    path:     /topico/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Topico:verTopico" }
    host:     %website%

forum_ver_mensagem:
    path:     /{slug_categoria}/{slug}
    defaults: { _controller: "PhpbrAppBundle:Forum\Mensagem:verMensagem" }
    host:     %website%

forum_novo_topico:
    path:     /novo
    defaults: { _controller: "PhpbrAppBundle:Forum\Topico:novo" }
    host:     %website%

forum_deletar:
    path:     /deletar/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Topico:deletar" }
    host:     %website%

forum_nova_mensagem:
    path:     /{topico_id}/novaMensagem
    defaults: { _controller: "PhpbrAppBundle:Forum\Mensagem:novaMensagem" }
    host:     %website%

forum_deletar_mensagem:
    path:     /deletar-mensagem/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Mensagem:deletarMensagem" }
    host:     %website%

forum_deletar_topico:
    path:     /deletar-topico/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Topico:deletarTopico" }
    host:     %website%
