forum_index:
    path:     /
    defaults: { _controller: "PhpbrAppBundle:Forum\Category:index" }
    host:     %website%

forum_view_category:
    path:     /categoria/{slug}
    defaults: { _controller: "PhpbrAppBundle:Forum\Category:viewCategory" }
    host:     %website%

forum_view_topic:
    path:     /topico/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Topic:ViewTopic" }
    host:     %website%

forum_view_message:
    path:     /{slug_categoria}/{slug}
    defaults: { _controller: "PhpbrAppBundle:Forum\Message:viewMessage" }
    host:     %website%

forum_new_topic:
    path:     /novo
    defaults: { _controller: "PhpbrAppBundle:Forum\Topic:new" }
    host:     %website%

forum_delete:
    path:     /deletar/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Topic:delete" }
    host:     %website%

forum_new_message:
    path:     /{topico_id}/novaMensagem
    defaults: { _controller: "PhpbrAppBundle:Forum\Message:newMessage" }
    host:     %website%

forum_delete_message:
    path:     /deletar-mensagem/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Message:deleteMessage" }
    host:     %website%

forum_delete_topic:
    path:     /deletar-topico/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Topic:deleteTopic" }
    host:     %website%
