forum_index:
    path:     /forum
    defaults: { _controller: "PhpbrAppBundle:Forum\Category:index" }

forum_view_category:
    path:     /forum/category/{slug}
    defaults: { _controller: "PhpbrAppBundle:Forum\Category:viewCategory" }

forum_view_topic:
    path:     /forum/topic/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Topic:ViewTopic" }

forum_view_message:
    path:     /forum/view-message/{slug_category}/{slug}
    defaults: { _controller: "PhpbrAppBundle:Forum\Message:viewMessage" }

forum_new_topic:
    path:     /forum/new
    defaults: { _controller: "PhpbrAppBundle:Forum\Topic:new" }

forum_new_message:
    path:     /forum/message/newMessage/{topic_id}/
    defaults: { _controller: "PhpbrAppBundle:Forum\Message:newMessage" }
    
forum_delete_topic:
    path:     /forum/topic/delete/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Topic:delete" }

forum_delete_message:
    path:     /forum/message/delete/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Message:deleteMessage" }
