fos_user_registration_register:
    path: /register/
    defaults: { _controller: FOSUserBundle:Registration:register }

fos_user_registration_confirmed:
    path: /register/confirmed
    defaults: { _controller: FOSUserBundle:Registration:confirmed }

fos_user_profile_show:
    path: /profile/
    defaults: { _controller: FOSUserBundle:Profile:show }

fos_user_profile_edit:
    path: /profile/edit
    defaults: { _controller: FOSUserBundle:Profile:edit }

fos_user_change_password:
    path: /change-password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }


