phpbr_app_main:
    path:     /
    defaults: { _controller: PhpbrAppBundle:Default:page, page: 'main' }

phpbr_app_whoweare:
    path:     /about
    defaults: { _controller: PhpbrAppBundle:Default:page, page: 'whoweare' }

phpbr_app_contact:
    path:     /contact
    defaults: { _controller: PhpbrAppBundle:Default:page, page: 'contact' }

phpbr_app_webchat:
    path:   /webchat
    defaults: { _controller: PhpbrAppBundle:Default:page, page: 'webchat' }

phpbr_app_viewuser:
    path:   /user/{user}
    defaults: { _controller: PhpbrAppBundle:Default:viewUser }
