lista_meus_artigos:
    path:   /
    defaults: { _controller: PhpbrAppBundle:Artigo:listaMeusArtigos }
    host:     %website%

deleta_meus_artigos:
    path: /{id}/deletar
    defaults: { _controller: PhpbrAppBundle:Artigo:deletar }
    host:     %website%

artigo_edit:
    path:     /{id}/editar
    defaults: { _controller: PhpbrAppBundle:Artigo:editar }
    host:     %website%

artigo_update:
    path:     /{id}/update
    defaults: { _controller: PhpbrAppBundle:Artigo:update }
    requirements: { _method: post|put }
    host:     %website%


