paste:
    path:     /
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:index" }

paste_pagina:
    path:     /pagina/{pagina}/
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:index", pagina:1 }

paste_ver:
    path:     /{id}
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:view" }
    requirements:
        id: \d+

paste_verRaw:
    path:     /{id}/ver-raw
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:viewRaw" }

paste_novo:
    path:     /novo
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:new" }

paste_create:
    path:     /criar
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:create" }
    methods:  POST

paste_edit:
    path:     /{id}/edit
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:edit" }

paste_update:
    path:     /{id}/update
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:update" }
    methods:  [POST, PUT]

paste_deletar:
    path:     /{id}/deletar 
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:delete" }
    methods:  [POST, DELETE]

