paste:
    path:     /
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:index" }

paste_page:
    path:     /page/{page}/
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:index", page:1 }

paste_view:
    path:     /{id}
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:view" }
    requirements:
        id: \d+

paste_viewRaw:
    path:     /{id}/view-raw
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:viewRaw" }

paste_new:
    path:     /new
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:new" }

paste_create:
    path:     /create
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:create" }
    methods:  POST

paste_edit:
    path:     /{id}/edit
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:edit" }

paste_update:
    path:     /{id}/update
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:update" }
    methods:  [POST, PUT]

paste_delete:
    path:     /{id}/delete
    host:     cole.php-br.org
    defaults: { _controller: "PhpbrAppBundle:Paste:delete" }
    methods:  [POST, DELETE]

