admin_artigos:
    path: /
    defaults: { _controller: "PhpbrAppBundle:Admin\Artigo:lista" }
    host:     %website%

admin_artigo_aprovar:
    path: /aprovar/{slug}
    defaults: { _controller: "PhpbrAppBundle:Admin\Artigo:aprovar" }
    host:     %website%

admin_artigo_anular:
    path: /anular/{slug}
    defaults: { _controller: "PhpbrAppBundle:Admin\Artigo:anular" }
    host:     %website%
