admin_articles:
    path: /admin/
    defaults: { _controller: "PhpbrAppBundle:Admin\Article:list" }

admin_article_approve:
    path: /admin/approve/{slug}
    defaults: { _controller: "PhpbrAppBundle:Admin\Article:approve" }

admin_article_refuse:
    path: /admin/refuse/{slug}
    defaults: { _controller: "PhpbrAppBundle:Admin\Article:refuse" }
