admin_forum_categories:
    path: /
    defaults: { _controller: "PhpbrAppBundle:Admin\Forum:index" }
    host:     %website%

admin_forum_new_category:
    path: /nova-categoria
    defaults: { _controller: "PhpbrAppBundle:Admin\Forum:newCategory" }
    host:     %website%

admin_forum_delete_category:
    path:     /{id}/deletar
    defaults: { _controller: "PhpbrAppBundle:Admin\Forum:delete" }
    host:     %website%