Phpbr\AppBundle\Entity\Forum\Topic:
    type: entity
    table: forum_topic
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        subject:
            type: string
            length: 255
        message:
            type: text
        createdAt:
            type: datetime
            column: created_at
        slug:
            type: string
            length: 255
            gedmo:
                slug:
                    separator: -
                    fields:
                        - id
                        - subject
    manyToOne:
        category:
            targetEntity: Phpbr\AppBundle\Entity\Forum\Category
            inversedBy: topics
            joinColumn:
                name: category_id
                referencedColumnName: id
                onDelete: CASCADE
        user:
            targetEntity: Phpbr\AppBundle\Entity\User
            inversedBy: topics
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }

    oneToMany:
        messages:
            targetEntity: Phpbr\AppBundle\Entity\Forum\Message
            mappedBy: topic
