Phpbr\AppBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: Phpbr\AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        linkedin:
            type: string
            length: 255
            nullable: true
        twitter:
            type: string
            length: 255
            nullable: true
        github:
            type: string
            length: 255
            nullable: true
        facebook_id:
            type: string
            length: 255
            nullable: true
        facebook_access_token:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
    oneToMany:
        articles:
            targetEntity: Article
            mappedBy: user
        messages:
            targetEntity: Phpbr\AppBundle\Entity\Forum\Message
            mappedBy: user
        topics:
            targetEntity: Phpbr\AppBundle\Entity\Forum\Topic
            mappedBy: user
        events:
            targetEntity: Phpbr\AppBundle\Entity\Event
            mappedBy: user

