Phpbr\AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 4
                max: 20
        github:
            - Regex:
                pattern: /^(https?:\/\/)?((w{3}\.)?)github.com\/.*/
                message: phpbr.registration.github.invalid
        twitter:
            - Regex:
                pattern: /^(https?:\/\/)?((w{3}\.)?)twitter.com\/.*/
                message: phpbr.registration.twitter.invalid

Phpbr\AppBundle\Entity\Article:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: title
    properties:
        title:
            - NotBlank: ~
            - Length:
                min: 4
                max: 155
        content:
            - NotBlank: ~
