admin_forum_categories:
    path:     /forum-admin/
    defaults: { _controller: "PhpbrAppBundle:Admin\Forum:index" }

admin_forum_new_category:
    path:     /forum-admin/new-category
    defaults: { _controller: "PhpbrAppBundle:Admin\Forum:newCategory" }

admin_forum_delete_category:
    path:     /forum-admin/{id}/delete
    defaults: { _controller: "PhpbrAppBundle:Admin\Forum:delete" }
